// Package types contains all the types associated to the goweather library : weather conditions, cities...
// Structures are not meant to be initialized by the user itself but only by the writer when editing the library.
package types
